os: Visual Studio 2015
platform: x64
shallow_clone: true
version: 1.0.{build}

environment:
  matrix:
    - GENERATOR: Visual Studio 14 2015
      CFG: Debug
    - GENERATOR: Visual Studio 14 2015
      CFG: Release
    - GENERATOR: Visual Studio 14 2015 Win64
      CFG: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      CFG: Release

build:
  parallel: true

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DBUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF -G "%GENERATOR%" ..
  - cmd: cmake --build . --config "%CFG%"

test_script:
  - cmd: cd test && ctest -C "%CFG%" -V
  
